output_dir: !!str ../output/cls
overwrite_output_dir: !!bool False
do_train: !!bool True
do_eval: !!bool False
do_predict: !!bool False
evaluate_during_training: !!bool False
per_device_train_batch_size: !!int 16
per_device_eval_batch_size: !!int 16
per_gpu_train_batch_size: !!int 16
per_gpu_eval_batch_size: !!int 16
gradient_accumulation_steps: !!int 1
learning_rate: !!float 5e-05
weight_decay: !!float 0.0
adam_epsilon: !!float 1e-08
max_grad_norm: !!float 1.0
num_train_epochs: !!int 1
max_steps: !!int -1
warmup_steps: !!int 0
logging_dir: !!str './log'
logging_first_step: !!bool False
logging_steps: !!int 1
save_steps: !!int 5
save_total_limit: !!int 3
no_cuda: !!bool False
seed: !!int 42
fp16: !!bool False
fp16_opt_level: !!str 'O1'
local_rank: -1
tpu_num_cores: !!int -1
tpu_metrics_debug: !!bool False
debug: !!bool False
dataloader_drop_last: !!bool False
eval_steps: !!int 2
past_index: !!int -1